import type { RedirectsConfig } from './types';

/** SEO redirect map — deploy in Prompt 3 (Netlify _redirects / Cloudflare / host rules) */
export const redirects: RedirectsConfig = {
  permanent: [
    { from: '/about-us/', to: '/about', reason: 'Arabic about page slug normalized' },
    { from: '/about-us', to: '/about', reason: 'Arabic about page slug normalized' },
    { from: '/contact-us/', to: '/contact', reason: 'Contact page slug normalized' },
    { from: '/contact-us', to: '/contact', reason: 'Contact page slug normalized' },
    { from: '/faqs/', to: '/faq', reason: 'FAQ page slug normalized' },
    { from: '/faqs', to: '/faq', reason: 'FAQ page slug normalized' },
    { from: '/home-1-2/', to: '/', reason: 'Old WordPress homepage slug' },
    { from: '/home-1-2', to: '/', reason: 'Old WordPress homepage slug' },
    {
      from: '/service/general-surgery/',
      to: '/services/general-surgery',
      reason: 'WooCommerce-style service URL → new structure',
    },
    {
      from: '/service/radiology/',
      to: '/services/laparoscopic-surgery',
      reason: 'Wrong WP slug (radiology) → laparoscopic surgery',
    },
    {
      from: '/service/orthopedics/',
      to: '/services/bariatric-surgery',
      reason: 'Wrong WP slug (orthopedics) → bariatric surgery',
    },
    {
      from: '/service/dental-care/',
      to: '/services/colorectal-surgery',
      reason: 'Wrong WP slug (dental-care) → colorectal surgery',
    },
    {
      from: '/service/pharmacology/',
      to: '/services/oncology-surgery',
      reason: 'Wrong WP slug (pharmacology) → oncology surgery',
    },
    {
      from: '/service/hematology/',
      to: '/services/endocrine-surgery',
      reason: 'Wrong WP slug (hematology) → endocrine surgery',
    },
    // Legitimate Arabic articles — old encoded URLs → clean /blog/ slugs
    {
      from: '/%d8%b9%d9%84%d8%a7%d8%ac-%d8%a7%d9%84%d8%a8%d9%88%d8%a7%d8%b3%d9%8a%d8%b1-%d8%a8%d8%a7%d9%84%d9%84%d9%8a%d8%b2%d8%b1-%d9%86%d9%87%d8%a7%d9%8a%d8%a9-%d8%b9%d8%b5%d8%b1-%d8%a7%d9%84%d8%a3%d9%84%d9%85/',
      to: '/blog/laser-hemorrhoids',
      reason: 'Laser hemorrhoids article',
    },
    {
      from: '/%d8%a7%d9%84%d8%aa%d8%b7%d9%88%d8%b1%d8%a7%d8%aa-%d8%a7%d9%84%d8%ad%d8%af%d9%8a%d8%ab%d8%a9-%d9%81%d9%8a-%d8%ac%d8%b1%d8%a7%d8%ad%d8%a9-%d8%a7%d9%84%d9%85%d9%86%d8%a7%d8%b8%d9%8a%d8%b1-%d8%ab%d9%88/',
      to: '/blog/laparoscopic-advances',
      reason: 'Laparoscopy article',
    },
    {
      from: '/%d8%ac%d8%b1%d8%a7%d8%ad%d8%a7%d8%aa-%d8%a7%d9%84%d8%b3%d9%85%d9%86%d8%a9-%d8%a3%d9%83%d8%b1%d9%87-%d9%85%d9%86-%d9%85%d8%ac%d8%b1%d8%af-%d9%81%d9%82%d8%af%d8%a7%d9%86-%d8%a7%d9%84%d9%88%d8%b2%d9%86/',
      to: '/blog/bariatric-surgery-guide',
      reason: 'Bariatric article',
    },
    {
      from: '/%d8%b3%d8%b1%d8%b7%d8%a7%d9%86-%d8%a7%d9%84%d9%82%d9%88%d9%84%d9%88%d9%86-%d8%a7%d9%84%d8%a7%d9%83%d8%aa%d8%b4%d8%a7%d9%81-%d8%a7%d9%84%d9%85%d8%a8%d9%83%d8%b1-%d9%8a%d9%86%d9%82%d8%b0-%d8%a7%d9%84%d8%a3%d8%b1%d9%88%d8%a7%d8%ad/',
      to: '/blog/colon-cancer-early-detection',
      reason: 'Colon cancer article',
    },
    {
      from: '/%d8%a7%d9%84%d8%ba%d8%af%d8%a9-%d8%a7%d9%84%d8%af%d8%b1%d9%82%d9%8a%d8%a9-%d9%85%d8%aa%d9%89-%d8%aa%d8%ad%d8%aa%d8%a7%d8%ac-%d9%84%d9%84%d8%ac%d8%b1%d8%a7%d8%ad%d8%a9/',
      to: '/blog/thyroid-surgery-guide',
      reason: 'Thyroid article',
    },
    {
      from: '/%d8%b3%d9%8a%d8%a7%d8%b3%d8%a9-%d8%a7%d9%84%d8%ae%d8%b5%d9%88%d8%b5%d9%8a%d8%a9/',
      to: '/privacy',
      reason: 'Arabic privacy policy URL',
    },
    {
      from: '/%d8%a7%d9%84%d8%b4%d8%b1%d9%88%d8%b7-%d9%88%d8%a7%d9%84%d8%a3%d8%ad%d9%83%d8%a7%d9%85/',
      to: '/terms',
      reason: 'Arabic terms URL',
    },
  ],

  gonePatterns: [
    { pattern: 'casino', description: 'Casino / iGaming spam' },
    { pattern: 'betting', description: 'Betting spam' },
    { pattern: 'slot', description: 'Slots spam' },
    { pattern: 'igaming', description: 'iGaming spam' },
    { pattern: 'vavada', description: 'Casino brand spam' },
    { pattern: 'pin-up', description: 'Casino brand spam' },
    { pattern: '1win', description: 'Betting spam' },
    { pattern: 'escort', description: 'Escort spam' },
    { pattern: 'porn', description: 'Adult spam' },
    { pattern: 'darknet', description: 'Darknet spam' },
    { pattern: 'omegle', description: 'Chat spam' },
    { pattern: 'kazino', description: 'Casino spam (transliterated)' },
  ],

  exactGonePaths: [
    '/shop/',
    '/shop',
    '/cart/',
    '/cart',
    '/checkout/',
    '/checkout',
    '/my-account/',
    '/my-account',
    '/wishlist/',
    '/wishlist',
    '/our-doctor/',
    '/doctor-detail/',
    '/location/',
    '/testimonial/',
    '/make-appoitment/',
    '/schedule/',
    '/billing-and-insurance/',
    '/our-history/',
    '/our-commitment/',
    '/blog-full-width/',
    '/home-2/',
    '/home-3/',
    '/home-4/',
    '/home-1-onepage/',
    '/home-2-onepage/',
    '/home-3-onepage/',
    '/home-4-onepage/',
    '/case-study-1/',
    '/case-study-2/',
    '/case-study-3/',
    '/case-study-4/',
    '/sample-page/',
  ],
};
